# Generated by Django 5.2 on 2025-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
