# Generated by Django 5.2 on 2025-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0003_profile_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='study_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='elapsed_seconds',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
