# Generated by Django 5.2 on 2025-08-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0005_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goal',
        ),
    ]
