# Generated by Django 5.2 on 2025-08-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0006_remove_profile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='streak',
            field=models.BooleanField(default=False),
        ),
    ]
