# Generated by Django 5.2 on 2025-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0007_goal_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='streak',
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.BooleanField(default=False),
        ),
    ]
