# Generated by Django 5.2 on 2025-08-26 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0008_remove_goal_streak_profile_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='streak',
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, null=True)),
                ('streak', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainuser_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
