# Generated by Django 5.2 on 2025-09-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0009_remove_profile_streak_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='chart',
            field=models.TextField(null=True),
        ),
    ]
