# Generated by Django 5.2 on 2025-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0010_goal_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='chart',
        ),
        migrations.AddField(
            model_name='profile',
            name='chart',
            field=models.TextField(null=True),
        ),
    ]
