# Generated by Django 5.2 on 2025-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwatch', '0011_remove_goal_chart_profile_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chart',
        ),
        migrations.AddField(
            model_name='profile',
            name='clock',
            field=models.TextField(null=True),
        ),
    ]
